language: node_js
node_js:
- 4.3.1
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  code_climate:
    repo_token: cd4e01d4cb05e80e15b2eebe560d212d7aab25fc25940ff157246d06f4c77ec2
deploy:
  provider: npm
  email: technique@yocto.re
  api_key:
    secure: cwPaQiy9mWdkNVMqPzVLY74vCeem4bwE8Cl80AXA4uFOw0c+S4XEAh6DNCweafiyPNbowKwN2oXLjqUfm3gghsAsWx2gTWwANgZpEVksfGC3QOXh50Sk6i5qZCG16zrPNxBVXBCbAbInFn4n81MzjsW5dLz3mORddk5gGV0HbBC1Wz4vfP2nE4s9tDxglFu7zkE03wKmBA7WlLvsOlNtsR+So26agdPv9+4HwITC0v9fHdxtyT5Cwf6vXDE8qoIs4tz2DDwSurV9nGX8BxbON3dAqsuIz0S6Bo7XlEpuhISMkZesxniQwe/C12jiQ6wFk70mWKgQVgIiS2NimGLNzupk7omYITZWOuEqKsx61+fp+Cm/bPQLASpGy9h7YMyurLUOrshbaJ0xh0j7A7aANW/4Q0Bshmv/D9U3twWD7x0BSEXuRLhpdxDEqX+IF+uQsa9EHdQCJz3T3jbaQ8ymsdMXCu8qrg8AUf+NLXpl5UjdWkPN7WjWV8zRGKwhnEW+lMSrifJF1ee7C5s9molDEKF3PcaaE9QhiIu7tpJN4e+shBQQRugXFfAN+clyqaJ/6dX8c5v1MPdccFXMf6nbPrINOEFs0+G9F8eGM0wK+V1oQTosl3tAU0YN/YaKd5fDTQbAiUVcWhTU185RuJf9ahYrYCzpLkazGQxWOyYradA=
  on:
    tags: true
    repo: yoctore/yocto-auth
before_install: npm install -g grunt-cli
install: npm install
